### ISSUE TITLE
Mouse over to reveal where a user has been

### ISSUE THREAD

**Issue by WBotzer** [nicholas-botzer/GraphGravity#15]

**Comment by DavidDailey** [comment]
Did we figure out when we are meeting?



D

________________________________

**Comment by deborahwhitfield** [comment]
Dave, I met with william and Eric on Saturday.
We will meet again via google hangout in a week or so.

Dr. Deborah Whitfield
Chair of Computer Science
SRU Coordinator of Undergraduate Research in STEM


On Jul 26, 2015, at 9:15 PM, DavidDailey <notifications@github.com<mailto:notifications@github.com>> wrote:

Did we figure out when we are meeting?



D

________________________________

**Comment by WBotzer** [comment]
Based on what Eric has on his granite, I noticed a bug. When a walker has completed a traversal, the onMouseOut event doesn't seem to work right.

**Comment by emcalpine** [comment]
Finished with yesterday's pushes
